// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uonxhnmvrtuszgjubvaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbnhobm12cnR1c3pnanVidmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzIzMTIsImV4cCI6MjA1NzE0ODMxMn0.yIJAmU3OLGXsZ5ar5L7kMo-CHL21FJWSnItbs7mOswo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);